# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_remove_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='haters',
        ),
    ]
