# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_record_haters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Item',
        ),
    ]
