# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20180420_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='album',
        ),
        migrations.RemoveField(
            model_name='item',
            name='artist',
        ),
    ]
